# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "Gionatan Buono's Website"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "© {year}"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2006-01-02"
  sourcePath = "gallery"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/Raptor803"
  email = "mailto:buono.gionatan@gmail.com"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["GitHub", "Email"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

  [params.gallerydeluxe]
    # Shuffle the images in the gallery to give the impression of a new gallery each time.
    shuffle = true

    # Reverse the order of the images in the gallery.
    reverse = false

      # Enable Exif data in the gallery.
      # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
    enable_exif = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  weight = 10
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"

[[menu.main]]
  weight = 11
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

#[[menu.main]]
#  weight = 20
#  identifier = "blog"
#  name = "blog"
#  title = "Blog"
#  url = "/blog"

[[menu.main]]
  weight = 30
  identifier = "gallery"
  name = "gallery"
  title = "Gallery"
  url = "/gallery"